//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int attendanceId { get; set; }
        public Nullable<System.DateTime> checkIn { get; set; }
        public Nullable<System.DateTime> checkOut { get; set; }
        public string totalHours { get; set; }
        public Nullable<bool> attendanceStatus { get; set; }
        public Nullable<int> employeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
