//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave
    {
        public int leaveId { get; set; }
        public Nullable<System.DateTime> statrtDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> totalDays { get; set; }
        public string leaveReason { get; set; }
        public Nullable<int> employeeId { get; set; }
        public Nullable<int> employeeRoleId { get; set; }
    }
}
